### ISSUE TITLE
Add in a "feedback" link

### ISSUE THREAD

**Issue by fils** [earthcube/geodexui#24]
Might be nice to have a feedback link on the page to allow people to report issues and also for providers to easily give feedback on any issues they discovery.

**Comment by MBcode** [comment]
help link to about.html has a link to these issues, and to the new feedback@earthcube.org

**Comment by MBcode** [comment]
More specific feedback@geocodes.earthcube.org that right now only goes to me, but if we see volume (from being in the newsletter)we will get it forwarded to an ecotech-dev channel again
