### ISSUE TITLE
Dataset search on "Steens Reversal" returns only tools, not datasets

### ISSUE THREAD

**Issue by njarboe** [earthcube/geodexui#57]
Dataset search on "Steens Reversal" returns only tools, not datasets.
![Screen Shot 2021-05-21 at 1 03 18 PM](https://user-images.githubusercontent.com/1278789/119193066-eb617d80-ba35-11eb-8c03-ac56cb3d579a.png)
![Screen Shot 2021-05-21 at 1 05 54 PM](https://user-images.githubusercontent.com/1278789/119193089-f7e5d600-ba35-11eb-9e87-c1ed993b782f.png)

Steens is also only found as keyword in one result.

**Comment by njarboe** [comment]
Searching on Steens does work as expected with dataset results. 

![Screen Shot 2021-05-21 at 1 27 28 PM](https://user-images.githubusercontent.com/1278789/119194718-5ad86c80-ba38-11eb-87f7-48e29a60b122.png)

Multi word search is not as useful as a single word if one cannot search for two words next to each other. Maybe think about the best way to suggest people use the best single word for what the are looking for. A search with **south American rain forest** gives many results in north America. I guess people know how these searches work but it is a bit counter intuitive that if you use more words to narrow your search one ends up expanding it.

In any case I would expect the search above on only datasets to not return any tools.

**Comment by valentinedwv** [comment]
Regression... MINUS filters for ResearchProject and People got dropped at some change.
Also, now using values, rather than BIND.
values (?type ?resourceType) {
            (schema:Dataset "data")
            (sschema:Dataset "data")
            (schema:ResearchProject "researchProject")
            (sschema:ResearchProject  "researchProject")
             (schema:SoftwareApplication  "tool")
             (sschema:SoftwareApplication  "tool")
             (schema:Person  "person")
             (sschema:Person  "person")
            (UNDEF "data") # make it work.
          } ?subj a ?type .
